esphome:
  name: nibegw
  comment: Nibegw

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# No API if you are using MQTT, password is optional
api:
  key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:

# Keep other SPI device CS pins HIGH to prevent interference
output:
  - platform: gpio
    pin: 
      number: GPIO21  # Display CS
      mode: output
    id: display_cs
    inverted: true  # Keep HIGH when off
  - platform: gpio
    pin:
      number: GPIO14  # LoRa CS
      mode: output
    id: lora_cs
    inverted: true  # Keep HIGH when off

psram:
  mode: octal
  speed: 80MHz

ethernet:
  type: W5500
  clk_pin: GPIO12
  mosi_pin: GPIO11
  miso_pin: GPIO13
  cs_pin: GPIO10
  interrupt_pin: GPIO9
  reset_pin: GPIO48
  clock_speed: 8MHz

# Load nibe component
external_components:
  - source: github://elupus/esphome-nibe

uart:
  rx_pin: GPIO18
  tx_pin: GPIO17
  baud_rate: 9600

# Configure NibeGW
nibegw:
  udp:
    # List of source address to accept data from, may be empty for no filter
    source:
      - 192.168.255.254

  acknowledge:
    - MODBUS40

  # Constant replies to certain requests cabe made
  constants:
    - address: MODBUS40
      token: ACCESSORY
      data: [
            0x0A, # MODBUS version low
            0x00, # MODBUS version high
            0x01, # MODBUS address?
      ]

# Some helper functions to restart ESPHome from HA
button:
- platform: restart
  name: Nibegw Restart